services:
  api1:
    image: molbr/rinha-backend-2026:latest
    pull_policy: always
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - GOMAXPROCS=1
      - LOOKUP_PATH=/resources/lookup.bin
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9999/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"
    restart: unless-stopped

  api2:
    image: molbr/rinha-backend-2026:latest
    pull_policy: always
    network_mode: "service:api1"
    environment:
      - PORT=9999
      - GOMAXPROCS=1
      - LOOKUP_PATH=/resources/lookup.bin
    depends_on:
      api1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9999/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"
    restart: unless-stopped
